<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>detpdf</ToolCommandName>
    <SignAssembly>false</SignAssembly>
    <RollForward>LatestMajor</RollForward>
    <PackageTags>pdf, deterministic, reproducible, cli, dotnet-tool</PackageTags>
    <Description>Command line tool that modifies PDF files to ensure they are deterministic. Helpful for testing, build reproducibility, security verification, and ensuring output integrity across different build environments.</Description>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CliFx" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <PackageReference Include="Microsoft.Sbom.Targets" PrivateAssets="all" Condition="'$(CI)' == 'true'" />
    <ProjectReference Include="..\DeterministicPdf\DeterministicPdf.csproj" />
  </ItemGroup>
</Project>
