<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <NoWarn>CS1591;CS0649;CA1416;NU1608;NU1109;NU1510</NoWarn>
    <Version>1.0.2</Version>
    <LangVersion>preview</LangVersion>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <Description>Modify PDF files to ensure they are deterministic. Helpful for testing, build reproducibility, security verification, and ensuring output integrity across different build environments.</Description>
    <ResolveAssemblyReferencesSilent>true</ResolveAssemblyReferencesSilent>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
  </PropertyGroup>
</Project>
